VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "AppCommands"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Property Get MyLogoutCommand() As ICommand
    Set MyLogoutCommand = NewActionCommand(NewFunction(Me, "MyLogoutCommandMethod"), True)
End Property

Public Sub MyLogoutCommandMethod()
    MsgBox "MyCommand :)"
End Sub
